### ISSUE TITLE
Restructure forcefield code

### ISSUE THREAD

**Issue by Djurredejong** [cgmartini/martinize.py#2]
With the growing number of forcefields, the code including them needs to be restructured.
I prefer if the standard options are include in the script and give the possibility to read separate files by the user. Bonus point is if also checks GMXDATA for possible Martini forcefields.
This would require:
- Separate out and rewrite the "catenate" definition.
- Move all ff files to a separate directory.

**Comment by Djurredejong** [comment]
I thought I had this implemented correctly (part of pull request #6 ), but it currently only works once the script is catenated. When working with the seperate modules it is currently broken....

**Comment by mdlab-jaakko** [comment]
Did commit c674e8115fb5811b613391de31245ef0f27477bb fix this? If it did this can be closed.

**Comment by Djurredejong** [comment]
Done and closed
