### ISSUE TITLE
Rewrite to python 3

### ISSUE THREAD

**Issue by Djurredejong** [cgmartini/martinize.py#3]
Well it is obvious it has to happen at some point...

**Comment by Djurredejong** [comment]
In branch 2to3 I think I've changed most that has to be changed. Actually everything that the "2to3" script suggested and everything else that gave error/crashes in my tests.

**Comment by mdlab-jaakko** [comment]
This is a tough one, don't think we should force people to install python3 (though as you said at some point it has to happen). Supporting two versions would mean making all changes in both. Whether that's worth the effort is up to you.

**Comment by Djurredejong** [comment]
Agreed that forcing an update to 3 isn't helping. Maintaining 2 versions is not so much work though: we make changes in the master branch and afterwards we merge them in the "2to3" branch. This will in 99% of the cases go without any manual intervention. I actually think this is where we will really feel the power of GIT! :-) Whether we want to put a Python3 version on cgmartini.nl, I don't know.
